name : Python CI/CD Example

# Trigger the workflow on any push to the main branch or pull request

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # step :check out code from repositry
            - name: check out the code
              uses: actions/checkout@v2


            # step 2:set up python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            # step 3: install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirment.txt

            # step 4: Run tests
            - name: Run tests
              run: pytest